AdGroupServiceBiddingStrategyConfiguration:
  type: object
  nullable: true
  properties:
    biddingScheme:
      $ref: 'AdGroupServiceBiddingScheme.yaml#/AdGroupServiceBiddingScheme'
  title: AdGroupServiceBiddingStrategyConfiguration
  description: |
    <div lang="ja">
    AdGroupServiceBiddingStrategyConfigurationは、広告グループ入札戦略を表します。<br>
    ADDおよびSET時、このフィールドは省略可能となります。<br>
    </div>
    <div lang="en">
    AdGroupServiceBiddingStrategyConfiguration object describes bidding strategy of ad group.<br>
    This field is optional in ADD and SET operation.<br>
    </div>
