CampaignServiceBiddingStrategyConfiguration:
  type: object
  nullable: true
  properties:
    biddingScheme:
      $ref: 'CampaignServiceBiddingScheme.yaml#/CampaignServiceBiddingScheme'
  title: CampaignServiceBiddingStrategyConfiguration
  description: |
    <div lang="ja">
    CampaignServiceBiddingStrategyConfigurationオブジェクトは、キャンペーン入札戦略です。<br>
    ADDおよびSET時、このフィールドは必須となります。<br>
    REMOVE時、このフィールドは無視されます。
    </div>
    <div lang="en">
    CampaignServiceBiddingStrategyConfiguration object describes campaign bidding strategy.<br>
    In ADD and SET operation, this field is required.<br>
    This field will be ignored in REMOVE operation.
    </div>
    
